MEMORY
{
  RAM : ORIGIN = 0x2000, LENGTH = 4K
  ROM : ORIGIN = 0x8000, LENGTH = 32K
  VECTORS : ORIGIN = 0xffc0, LENGTH = 0x40
}

REGION_ALIAS("REGION_TEXT", ROM);
REGION_ALIAS("REGION_RODATA", ROM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);